routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('/feed/{id}', ['as' => 'feed', 'uses' => 'HomeController@show']);

Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', ['as' => 'login.submit', 'uses' => 'Auth\LoginController@login']);
Route::get('logout', ['as' => 'logout', 'middleware' => ['auth'], 'uses' => 'Auth\LoginController@logout']);

# Admin
Route::group(['middleware' => ['auth'], 'namespace' => 'Admin', 'prefix' => 'admin'], function ()
{
    Route::resource('feed_urls', 'FeedUrlsController', ['except' => ['show', 'destroy']]);
    Route::get('feed_urls/{id}/destroy', ['as' => 'feed_urls.destroy', 'uses' => 'FeedUrlsController@destroy']);

    Route::get('my_account/change_password', ['as' => 'my_account.change_password_form', 'uses' => 'MyAccountController@showChangePasswordForm']);
    Route::post('my_account/change_password', ['as' => 'my_account.change_password', 'uses' => 'MyAccountController@changePassword']);
});

app/Feed.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

class Feed extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'feed_url_id', 'title', 'description', 'url', 'publish_date'
    ];

    public $timestamps = false;

    public function feedUrl() {
        return $this->hasOne('App\FeedUrl', 'id', 'feed_url_id');
    }
}

app/FeedUrl.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

class FeedUrl extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'url'
    ];

}

app/User.php
<?php
namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }
}

app/Http/Controllers/Admin/FeedUrlsController.php
<?php

namespace App\Http\Controllers\Admin;


use App\Http\Controllers\Controller;
use App\Repositories\FeedUrl\FeedUrlRepositoryInterface;
use Illuminate\Http\Request;

class FeedUrlsController extends Controller
{
    /**
     * View feed urls list if it's an ajax request or else show feed urls page with a list
     *
     * @param Request $request
     * @param FeedUrlRepositoryInterface $feedUrlRepository
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request, FeedUrlRepositoryInterface $feedUrlRepository)
    {
        $items = $feedUrlRepository->all();

        return view('admin.feedUrls.'.($request->ajax() ? 'list' : 'index'), compact('items'));
    }

    /**
     * View feed urls create form
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('admin.feedUrls.create');
    }

    /**
     * Validate feed urls create request and create feed url
     *
     * @param Request $request
     * @param FeedUrlRepositoryInterface $feedUrlRepository
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request, FeedUrlRepositoryInterface $feedUrlRepository)
    {
        $this->validateRequest($request);

        $feedUrlRepository->create([
            'title' => $request->get('title'),
            'url' => $request->get('url')
        ]);

        return redirect()->route('feed_urls.index')->with('success', 'Feed URl created successfully!');
    }

    /**
     * View feed url edit form
     *
     * @param $id
     * @param FeedUrlRepositoryInterface $feedUrlRepository
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id, FeedUrlRepositoryInterface $feedUrlRepository)
    {
        $item = $feedUrlRepository->find($id);

        return view('admin.feedUrls.edit', compact('item'));
    }

    /**
     * Validate feed url edit request and update feed url
     *
     * @param $id
     * @param Request $request
     * @param FeedUrlRepositoryInterface $feedUrlRepository
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id, Request $request, FeedUrlRepositoryInterface $feedUrlRepository)
    {
        $this->validateRequest($request);

        $feedUrlRepository->update($id, [
            'title' => $request->get('title'),
            'url' => $request->get('url')
        ]);

        return redirect()->route('feed_urls.index')->with('success', 'Feed URl updated successfully!');
    }

    /**
     * Destroy feed url
     *
     * @param $id
     * @param FeedUrlRepositoryInterface $feedUrlRepository
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id, FeedUrlRepositoryInterface $feedUrlRepository)
    {
        $feedUrlRepository->delete($id);

        return redirect()->route('feed_urls.index')->with('success', 'Feed URl removed successfully!');
    }

    /**
     * Validate feed url edit and create request
     *
     * @param $request
     */
    private function validateRequest($request)
    {
        $this->validate($request, [
            'title' => 'required',
            'url' => 'required|active_url'
        ]);
    }
}

app/Http/Controllers/Admin/MyAccountController.php
<?php

namespace App\Http\Controllers\Admin;


use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class MyAccountController extends Controller
{
    /**
     * View change password form
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function showChangePasswordForm()
    {
        return view('admin.myAccount.changePassword');
    }

    /**
     * Validate change password request and update user password
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function changePassword(Request $request)
    {
        $this->validate($request, [
            'password' => 'required',
            'password_confirmation' => 'required|same:password'
        ]);

        Auth::User()->password = $request->get('password');
        Auth::User()->save();

        return redirect()->route('home')->with('success', 'Password updated successfully!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;


use App\Repositories\Feed\FeedRepositoryInterface;
use App\Repositories\FeedUrl\FeedUrlRepositoryInterface;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * View latest feeds list if it's an ajax request or else show feeds page with a list
     *
     * @param Request $request
     * @param FeedRepositoryInterface $feedRepository
     * @param FeedUrlRepositoryInterface $feedUrlRepository
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request, FeedRepositoryInterface $feedRepository, FeedUrlRepositoryInterface $feedUrlRepository)
    {
        $filter = $request->get('filter');

        $items = $feedRepository->getLatest($filter);

        $filters = array_merge(['0' => 'Show all'], $feedUrlRepository->pluck('title', 'id'));

        return view('home.'.($request->ajax() ? 'list' : 'index'), compact('items', 'filters'));
    }

    /**
     * @param $id
     * @param FeedRepositoryInterface $feedRepository
     * @return mixed
     */
    public function show($id, FeedRepositoryInterface $feedRepository)
    {
        return $feedRepository->find($id);
    }
}

resources/views/admin/feedUrls/create.blade.php
@extends('layout')

@section('content')
    <form action="{{ route('feed_urls.store') }}" method="POST">
        {{ csrf_field() }}
        <div class="form-group">
            <label for="inputTitle">Title</label>
            <input name="title" type="text" id="inputTitle" class="form-control" required autofocus>
        </div>
        <div class="form-group">
            <label for="inputUrl">URL</label>
            <input name="url" type="text" id="inputUrl" class="form-control" required>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>
    </form>
@stop

resources/views/admin/feedUrls/edit.blade.php
@extends('layout')

@section('content')
    <form action="{{ route('feed_urls.update', [$item->id]) }}" method="POST">
        {{ csrf_field() }}
        <input name="_method" type="hidden" value="PUT">
        <div class="form-group">
            <label for="inputTitle">Title</label>
            <input name="title" type="text" id="inputTitle" class="form-control" value="{{ $item->title }}" required autofocus>
        </div>
        <div class="form-group">
            <label for="inputUrl">URL</label>
            <input name="url" type="text" id="inputUrl" class="form-control" value="{{ $item->url }}" required>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Edit</button>
    </form>
@stop

resources/views/admin/feedUrls/index.blade.php
@extends('layout')

@section('content')
    <div>
        <a href="{{ route('feed_urls.create') }}" class="btn btn-success">Add feed URL</a>
    </div>
    <div id="feeds-list">
        @include('admin.feedUrls.list')
    </div>
@stop

resources/views/admin/feedUrls/list.blade.php
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Title</th>
            <th>URL</th>
            <th>Actions</th>
        </tr>
    </thead>
    <thead>
        @foreach($items as $item)
            <tr>
                <td>{{ $item->title }}</td>
                <td>{{ $item->url }}</td>
                <td><a href="{{ route('feed_urls.edit', [$item->id]) }}" class="btn btn-warning btn-xs">Edit</a> <a href="{{ route('feed_urls.destroy', [$item->id]) }}" class="btn btn-danger btn-xs">Delete</a></td>
            </tr>
        @endforeach
    </thead>
</table>

resources/views/admin/myAccount/changePassword.blade.php
@extends('layout')

@section('content')
    <form action="{{ route('my_account.change_password') }}" method="POST">
        {{ csrf_field() }}
        <div class="form-group">
            <label for="inputPassword">Password</label>
            <input name="password" type="password" id="inputPassword" class="form-control" required autofocus>
        </div>
        <div class="form-group">
            <label for="inputPasswordConfirmation">Password confirmation</label>
            <input name="password_confirmation" type="password" id="inputPasswordConfirmation" class="form-control" required>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>
    </form>
@stop

resources/views/home/index.blade.php
@extends('layout')

@section('content')
    <p>
        <select name="filter" class="form-control">
            @foreach($filters as $key => $value)
                <option value="{{ $key }}">{{ $value }}</option>
            @endforeach
        </select>
    </p>
    <ul id="feeds-list">
        @include('home.list')
    </ul>

    <!-- Modal -->
    <div class="modal fade" id="feedModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel"></h4>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close the modal</button>
                    <a href="#" class="btn btn-primary modal-link" target="_blank">Go to feed page</a>
                </div>
            </div>
        </div>
    </div>
@stop

@section('javascript')
    <script src="{{ asset('js/app.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('select[name="filter"]').on('change', function () {
                var val = $(this).val();
                $.ajax({
                    url: "{{ route('home') }}",
                    data: {
                        filter: val
                    },
                    beforeSend: function () {
                        $("#feeds-list").css('opacity', 0.5);
                    },
                    success: function(result){
                        $("#feeds-list").html(result).css('opacity', 1);
                    }
                });
            });

            $(document).on('click', '.feed-modal-open', function (e) {
                e.preventDefault();

                var el = $(this);
                var url = el.attr('href');
                var mod = $('#feedModal');
                $.ajax({
                    url: url,
                    success: function(result){
                        mod.find('.modal-title').html(result.title);
                        mod.find('.modal-body').html(result.description);
                        mod.find('.modal-link').attr('href', result.url);
                        console.log(result.url);
                        mod.modal('show');
                    }
                });
            });
        });
    </script>
@stop

resources/views/home/list.blade.php
@foreach($items as $item)
    <li>[{{ $item->feed_url_title }}] <a href="{{ route('feed', [$item->id]) }}" class="feed-modal-open">{{ $item->title }}</a> [{{ $item->publish_date }}]</li>
@endforeach

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>News aggregator</title>
        <link rel="stylesheet" href="{{ asset('css/bootstrap.css') }}">
        <link rel="stylesheet" href="{{ asset('css/jumbotron-narrow.css') }}">
    </head>
    <body>

    <div class="container">
        <div class="header clearfix">
            <nav>
                <ul class="nav nav-pills pull-right">
                    <li role="presentation" class="active"><a href="{{ route('home') }}">Latest feeds</a></li>
                    @if (Auth::check())
                        <li role="presentation"><a href="{{ route('feed_urls.index') }}">Manage feeds</a></li>
                        <li role="presentation"><a href="{{ route('my_account.change_password') }}">Change password</a></li>
                        <li role="presentation"><a href="{{ route('logout') }}">Logout</a></li>
                    @else
                        <li role="presentation"><a href="{{ route('login') }}">Login</a></li>
                    @endif
                </ul>
            </nav>
            <h3 class="text-muted">News aggregator</h3>
        </div>
        @if (isset($errors) && count($errors))
            <ul class="alert alert-danger">
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif
        @if (Session::has('success'))
            <div class="alert alert-success">{{ Session::get('success') }}</div>
        @endif
        @yield('content')

        <footer class="footer">
            <p>&copy; 2016 Company, Inc.</p>
        </footer>
    </div> <!-- /container -->
    <script src="{{ asset('js/jquery-3.1.1.min.js') }}"></script>

    @yield('javascript')
    </body>
</html>